apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci_app_deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci_app_pipeline
  template:
    metadata:
      labels:
        app: ci_app_pipeline
    spec:
      containers:
        - name: pipeline-project
          image: dcolanderjr/ci_app_pipeline:1.0.0-21
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
