apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci-app
  template:
    metadata:
      labels:
        app: ci-app
    spec:
      containers:
        - name: ci-app
          image: dcolanderjr/ci_app_pipeline:1.0.0-44
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
